version: '3.9'
services:
  web:
    build: .
    container_name: web
    env_file:
      - .env
    ports:
      - "13234:1323"
    volumes:
      - .:/src/app/backend
    command: air ./main.go -b 0.0.0.0
    networks:
      - lineoa-klaeng-network
  db:
    image: postgres:alpine
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - lineoa-klaeng-network

volumes:
  postgres-db:

networks:
  lineoa-klaeng-network:
