version: '3.8'
services:
  db:
    image: postgres:15.1
    environment:
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: gorm
      POSTGRES_DB: gorm
      POSTGRES_SSLMODE: disable
    ports:
      - "9920:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
