version: '3.9'
services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "1323:1323"
    volumes:
      - .:/usr/src/app/lineoa-klaeng/backend
    command: air ./main.go -b 0.0.0.0
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
